# Each new term in the Fibonacci sequence is
# generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms
# will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci
# sequence whose values do not exceed four
# million, find the sum of the even-valued terms.
class EvenFibo
  def self.sum(limit)
    fibs = [1, 1]
    next_fib = 0

    loop do
      next_fib = fibs[-2] + fibs[-1]

      break if next_fib > limit

      fibs << next_fib
    end

    fibs.select { |i| i.even? }.inject(:+)
  end
end
